HGKNews/Controllers/NewsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HGKNews.Entities;
using HGKNews.Factories.Abstract;
using HGKNews.Services.Abstract;
using HGKNews.Models.NewsItem;
using OfficeOpenXml;
using HGKNews.Context;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Razor.Compilation;
using HGKNews.Factories;
using Microsoft.IdentityModel.Tokens;

namespace HGKNews.Controllers
{
    public class NewsController : Controller
    {
        #region Fields
        private readonly INewsRepository _newsRepository;
        private readonly IMapper _mapper;
        private readonly INewsItemModelFactory _newsItemModelFactory;
        #endregion

        #region Ctor
        public NewsController(INewsRepository newsRepository, IMapper mapper, INewsItemModelFactory newsItemModelFactory)
        {
            _newsRepository = newsRepository ?? throw new ArgumentNullException(nameof(newsRepository));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
            _newsItemModelFactory = newsItemModelFactory ?? throw new ArgumentNullException(nameof(newsItemModelFactory));
        }
        #endregion

        #region Methods

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var model = await _newsItemModelFactory.PrepareNewsItemModelForListAsync(new NewsItemModel());
            var sortedNews = model.OrderByDescending(news => news.CreateOn).ToList();
            return View("List", sortedNews);
        }

        [HttpGet("News/Details/{newsId}")]
        public async Task<IActionResult> Details(int newsId)
        {
            var news = await _newsRepository.GetNewsByIdAsync(newsId);
            var newsModel = _mapper.Map<NewsItemModel>(news);

            return View("Details", newsModel);
        }

        [HttpGet]
        public async Task<IActionResult> NewsTable()
        {
            var model = await _newsItemModelFactory.PrepareNewsItemModelForListAsync(new NewsItemModel());
            return View("NewsTable", model);
        }
        [HttpPost]
        public async Task<IActionResult> List(NewsItemModel model)
        {
            var newsItemModel = await _newsItemModelFactory.PrepareNewsItemModelForListAsync(model);
            return View(newsItemModel);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {

            var model = await _newsItemModelFactory.PrepareNewsItemModelAsync(new NewsItemModel(), null);

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Create(NewsItemModel news)
        {
            var finalNews = _mapper.Map<NewsItem>(news);

            await _newsRepository.AddNewsAsync(finalNews);

            return RedirectToAction("List");
        }

        [HttpGet("News/Edit/{newsId}")]
        public async Task<IActionResult> Edit(int newsId)
        {
            var newsItem = await _newsRepository.GetNewsByIdAsync(newsId);

            if (newsItem == null)
            {
                return NotFound();
            }

            var newsModel = await _newsItemModelFactory.PrepareNewsItemModelAsync(null, newsItem);

            return View(newsModel);
        }


        [HttpPost("News/Edit/{newsId}")]
        public async Task<IActionResult> Edit(int newsId, NewsItemModel newsItemModel)
        {
            var existingNews = await _newsRepository.GetNewsByIdAsync(newsId);
            if (existingNews == null)
            {
                return NotFound();
            }

            existingNews.Title = newsItemModel.Title;
            existingNews.Content = newsItemModel.Content;
            existingNews.Author = newsItemModel.Author;
            existingNews.NewsDate = newsItemModel.NewsDate;
            existingNews.Category = newsItemModel.Category;
            existingNews.Country = newsItemModel.Country;

            _mapper.Map<NewsItem>(existingNews);

            await _newsRepository.EditNewsAsync(newsId, existingNews);

            return RedirectToAction("List");
        }



        [HttpPost]
        public async Task<IActionResult> Delete(int newsId)
        {
            var newsEntity = await _newsRepository.GetNewsByIdAsync(newsId);

            if (newsEntity == null)
            {
                return NotFound();
            }

            await _newsRepository.DeleteNewsAsync(newsId);

            return RedirectToAction("List");
        }

        [HttpGet]
        public IActionResult ExportExcel()
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            List<NewsItemModel> newsItemModels = _newsRepository.GetNewsList();

            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add("Report");

                worksheet.Cells["A3"].Value = "Downloaded At";
                worksheet.Cells["B3"].Value = DateTimeOffset.Now.ToString("dd MM yyyy") + DateTimeOffset.Now.ToString("H:mm tt");

                var headers = new List<string> { "Id", "Title", "Content", "Author", "CreateOn", "NewsDate", "Category", "Country", "NewsPicture" };
                for (int i = 0; i < headers.Count; i++)
                {
                    worksheet.Cells[6, i + 1].Value = headers[i];

                    var cell = worksheet.Cells[6, i + 1];
                    var fill = cell.Style.Fill;
                    fill.PatternType = OfficeOpenXml.Style.ExcelFillStyle.Solid;
                    fill.BackgroundColor.SetColor(System.Drawing.Color.LightGray);
                }

                int rowStart = 7;

                foreach (var item in newsItemModels)
                {
                    worksheet.Cells[rowStart, 1].Value = item.Id;
                    worksheet.Cells[rowStart, 2].Value = item.Title;
                    worksheet.Cells[rowStart, 3].Value = item.Content;
                    worksheet.Cells[rowStart, 4].Value = item.Author;
                    worksheet.Cells[rowStart, 5].Value = item.CreateOn.ToString("dd.MM.yyyy HH:mm:ss");
                    worksheet.Cells[rowStart, 6].Value = item.NewsDate.ToString("dd.MM.yyyy");
                    worksheet.Cells[rowStart, 7].Value = item.Category;
                    worksheet.Cells[rowStart, 8].Value = item.Country;
                    worksheet.Cells[rowStart, 9].Value = item.NewsPicture;
                    rowStart++;
                }

                worksheet.Cells[worksheet.Dimension.Address].AutoFitColumns();

                var content = package.GetAsByteArray();

                return File(content, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "NewsDataTable.xlsx");
            }
        }

        [HttpPost]
        public async Task<IActionResult> ImportExcel(IFormFile file)
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            if (file == null || file.Length == 0)
            {
                ModelState.AddModelError(string.Empty, "Choose an Excel file.");
                return View();
            }

            using (var stream = new MemoryStream())
            {
                await file.CopyToAsync(stream);
                using (var package = new ExcelPackage(stream))
                {
                    var worksheet = package.Workbook.Worksheets[0];

                    int rowCount = worksheet.Dimension.Rows;

                    var newsItems = new List<NewsItem>();

                    for (int row = 2; row <= rowCount; row++)
                    {
                        var item = new NewsItemModel
                        {
                            Title = worksheet.Cells[row, 2].Value?.ToString() ?? "",
                            Content = worksheet.Cells[row, 3].Value?.ToString() ?? "",
                            Author = worksheet.Cells[row, 4].Value?.ToString() ?? "",
                            NewsDate = DateTime.TryParse(worksheet.Cells[row, 6].Text, out DateTime newsDate)
                                ? newsDate
                                : DateTime.MinValue,
                            Category = worksheet.Cells[row, 7].Value?.ToString() ?? "",
                            Country = worksheet.Cells[row, 8].Value?.ToString() ?? "",
                        };
                        if (worksheet.Cells[1, 2].Value != "Title"
                            && worksheet.Cells[1, 3].Value != "Content"
                            && worksheet.Cells[1, 4].Value != "Author"
                            && worksheet.Cells[1, 5].Value != "NewsDate"
                            && worksheet.Cells[1, 6].Value != "CreateOn"
                            && worksheet.Cells[1, 7].Value != "Category"
                            && worksheet.Cells[1, 8].Value != "Country")
                        {
                            return RedirectToAction("NewsTable");
                        }
                        else
                        {
                            if (item.Title != "" || item.Content != "" || item.Author != "" || item.Category != "" || item.Country != "")
                            {
                                item.CreateOn = DateTime.Now;
                                var finalNews = _mapper.Map<NewsItem>(item);
                                await _newsRepository.AddNewsAsync(finalNews);
                            }
                        }
                    }
                }
            }
            return RedirectToAction("NewsTable");
        }
    }
}

#endregion

HGKNews/Views/News/Create.cshtml
@using HGKNews.Models.NewsItem;
@model NewsItemModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    function clearForm() {
        document.getElementById("Title").value = "";
        document.getElementById("Content").value = "";
        document.getElementById("NewsPicture").value = "";
        document.getElementById("Country").value = "";
        document.getElementById("Author").value = "";
        document.getElementById("Category").value = "";
        document.getElementById("NewsDate").value = "";
    }

</script>
<div class="container mt-4">
    <div class="d-flex justify-content-between">
        <h2>Create News</h2>
        <div>
            <button type="button" onclick="clearForm()" class="btn btn-warning">Clear Form</button>
            <button type="submit" form="createNewsForm" class="btn btn-primary">Save</button>
        </div>
    </div>
    <hr />

    <form asp-action="Create" method="post" enctype="multipart/form-data" id="createNewsForm">
        <div class="form-group">
            <label for="Title">Title</label>
            <input type="text" class="form-control" id="Title" name="Title" required />
        </div>
        <div class="form-group">
            <label for="Author">Author</label>
            <input type="text" class="form-control" id="Author" name="Author" required />
        </div>
        <div class="form-group">
            <label for="Country">Country</label>
            <select class="form-control" id="Country" name="Country" required>
                <option value="">Select a country</option>
                <option value="Afghanistan">Afghanistan</option>
                <option value="Albania">Albania</option>
                <option value="Algeria">Algeria</option>
                <option value="Andorra">Andorra</option>
                <option value="Angola">Angola</option>
                <option value="Antigua and Barbuda">Antigua and Barbuda</option>
                <option value="Argentina">Argentina</option>
                <option value="Armenia">Armenia</option>
                <option value="Australia">Australia</option>
                <option value="Austria">Austria</option>
                <option value="England">England</option>
                <option value="Turkey">Turkey</option>
            </select>
        </div>
        <div class="form-group">
            <label for="NewsDate">News Date</label>
            <input type="date" class="form-control" id="NewsDate" name="NewsDate" required />
        </div>
        <div class="form-group">
            <label for="Category">Category</label>
            <input type="text" class="form-control" id="Category" name="Category" required />
        </div>
        <div class="form-group">
            <label for="Content">Content</label>
            <textarea class="form-control" id="Content" name="Content" rows="5" required></textarea>
        </div>

        <div class="form-group mt-4">
            <label for="NewsPicture">Resim Yükle</label>
            <input type="file" class="form-control-file" id="NewsPicture" name="NewsPicture" accept="image/*" required />
        </div>
    </form>
</div>

HGKNews/Views/News/Details.cshtml
@using HGKNews.Models.NewsItem;
@model NewsItemModel

    <div id="pdfarea" class="container mt-4">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h2>@Model.Title</h2>
                <p>Create Date : @Model.CreateOn.ToShortDateString()</p>
                <p>News Date : @Model.NewsDate.ToShortDateString()</p>
                <p>Author : @Model.Author</p>
                <p>Category : @Model.Category</p>
                <p>Country : @Model.Country</p>
                <h3>Content : </h3>
                <p>@Model.Content</p>
                @if (Model.NewsPicture != null && Model.NewsPicture.Length > 0)
                {
                    var base64Image = Convert.ToBase64String(Model.NewsPicture);
                    <img src="data:image/png;base64,@base64Image" class="img-fluid" alt="Haber Resmi">
                }
                <a href="@Url.Action("Index", "Home")" class="btn btn-primary">Ana Sayfaya Dön</a>
                <a href="@Url.Action("List", "News")" class="btn btn-primary">Haberlere Dön</a>
                <button class="btn btn-primary" id="downloadPDF"> Download PDF</button>
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
    <script>
        document.getElementById('downloadPDF').addEventListener("click", () => {
            const invoice = this.document.getElementById('pdfarea');
            var opt = {
                margin: 1,
                border:1,
                filename: "@Model.Title-HGKNews.pdf",
                Image: { type: 'jpeg' },
            }
            html2pdf().from(invoice).set(opt).save();
        })
    </script>

HGKNews/Views/News/Edit.cshtml
@using HGKNews.Models.NewsItem;
@model NewsItemModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script>
    function clearForm() {
        document.getElementById("Title").value = "";
        document.getElementById("Content").value = "";
        document.getElementById("NewsPicture").value = "";
        document.getElementById("Country").value = "";
        document.getElementById("Author").value = "";
        document.getElementById("Category").value = "";
        document.getElementById("NewsDate").value = "";
    }

</script>
<div class="container mt-4">
    <div class="d-flex justify-content-between">
        <h2>Edit News</h2>
        <div>
            <form method="post" action="@Url.Action("Delete", "News", new { newsId = Model.Id })" style="display: inline;">
                @Html.Hidden("newsId", Model.Id)
                <button type="submit" class="btn btn-danger" onclick="return confirm('Bu haberi silmek istediğinize emin misiniz?')">Delete</button>
            </form>
            <button type="button" onclick="clearForm()" class="btn btn-warning">Clear Form</button>
            <button type="submit" form="editForm" class="btn btn-primary">Save</button>
        </div>

    </div>
    <hr />

    <form asp-action="Edit" method="post" enctype="multipart/form-data" id="editForm">
        <div class="form-group">
            <label for="Title">Title</label>
            <input type="text" class="form-control" id="Title" name="Title" value="@Model.Title" required />
        </div>
        <div class="form-group">
            <label for="Author">Author</label>
            <input type="text" class="form-control" id="Author" name="Author" value="@Model.Author" required />
        </div>
        <div class="form-group">
            <label for="Country">Country</label>
            <select class="form-control" id="Country" name="Country" required>
                <option value="@Model.Country">@Model.Country</option>
                <option value="Afghanistan">Afghanistan</option>
                <option value="Albania">Albania</option>
                <option value="Algeria">Algeria</option>
                <option value="Andorra">Andorra</option>
                <option value="Angola">Angola</option>
                <option value="Antigua and Barbuda">Antigua and Barbuda</option>
                <option value="Argentina">Argentina</option>
                <option value="Armenia">Armenia</option>
                <option value="Australia">Australia</option>
                <option value="Austria">Austria</option>
                <option value="England">England</option>
                <option value="Turkey">Turkey</option>
            </select>
        </div>
        <div class="form-group">
            <label for="NewsDate">News Date</label>
            <input type="text" class="form-control" id="NewsDate" name="NewsDate" value="@Model.NewsDate.ToString("dd.MM.yyyy")" required />
        </div>
        <div class="form-group">
            <label for="Category">Category</label>
            <input type="text" class="form-control" id="Category" name="Category" value="@Model.Category" required />
        </div>
        <div class="form-group">
            <label for="Content">Content</label>
            <textarea class="form-control" id="Content" name="Content" rows="5" required>@Model.Content</textarea>
        </div>

        <div class="form-group mt-4">
            <label for="NewsPicture">Resim Yükle</label>
            <input type="file" class="form-control-file" id="NewsPicture" name="NewsPicture" value="@Model.NewsPicture" accept="image/*" />
        </div>
    </form>
</div>

HGKNews/Views/News/List.cshtml
@using HGKNews.Models.NewsItem;
@model IEnumerable<NewsItemModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4">
    <h2>Search</h2>
    <hr />

    <form asp-action="List" method="post" class="mb-4">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search News..." name="searchQuery">
            <button type="submit" class="btn btn-primary">Search</button>
            <button type="button" onclick="clearSearch()" class="btn btn-secondary ms-3">Clear Search</button>
        </div>
    </form>
</div>
<script>
    function clearSearch() {
        document.querySelector('input[name="searchQuery"]').value = '';
        document.querySelector('form').submit();
    }
</script>
<div class="container mt-4 mb-5">
    <h2>News</h2>
    <hr />

    <div class="row row-cols-1 row-cols-md-3 g-4">
        @foreach (var news in Model)
        {
            <div class="col">
                <div class="card h-100">
                    @if (news.NewsPicture != null && news.NewsPicture.Length > 0)
                    {
                        var base64Image = Convert.ToBase64String(news.NewsPicture);
                        <img src="data:image/png;base64,@base64Image" class="card-img-top" alt="News Picture">
                    }
                    else
                    {
                        <img src="~/images/11796.jpg" class="card-img-top" alt="Default Picture">
                    }
                <div class="card-body">
                    <h5 class="card-title">@news.Title</h5>
                    @{
                        string truncatedContent = news.Content.Length > 15
                            ? news.Content.Substring(0, 15) + "..."
                            : news.Content;
                    }
                    <p class="card-text">@truncatedContent</p>

                </div>
                    <div class="card-footer">
                        <a href="@Url.Action("Details", "News", new {id = news.Id })" class="btn btn-primary">Read More</a>
                        <a href="@Url.Action("Edit", "News", new {id = news.Id })" class="btn btn-warning">Edit</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

HGKNews/Views/News/NewsTable.cshtml
@using HGKNews.Models.NewsItem;
@model IEnumerable<NewsItemModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1 class="mb-4">NewsTable</h1>
<div class="container">
    <div class="row">
        <div class="col-md-1">
            <a class="btn btn-success mb-4" href="@Url.Action("ExportExcel","News")">Export</a>
        </div>
        <div class="col-md-1 ">
            <form asp-controller="News" asp-action="ImportExcel" method="post" enctype="multipart/form-data">
                    <input type="file" name="file" class="form-control-file d-none" id="fileInput" accept=".xlsx" required />
                    <button type="button" class="btn btn-primary" onclick="document.getElementById('fileInput').click();">Import</button>
            </form>
        </div>
    </div>
</div>
<div class="container">
    <table id="example" class="table table-striped mt-4" style="width:100%">
        <thead>
            <tr>
                <th>Title</th>
                <th>Author</th>
                <th>Category</th>
                <th>Create Date</th>
                <th>News Date</th>
                <th>Country</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var news in Model)
            {
                <tr>
                    <td><a href="@Url.Action("Details", "News", new {id = news.Id })"> @news.Title</a></td>
                    <td>@news.Author</td>
                    <td>@news.Category</td>
                    <td>@news.CreateOn</td>
                    <td>@news.NewsDate.ToString("dd.MM.yyyy")</td>
                    <td>@news.Country</td>
                    <td><a class="btn btn-danger" href="@Url.Action("Edit", "News", new {id = news.Id })">Edit</a> <a class="btn btn-danger" href="@Url.Action("Details", "News", new {id = news.Id })">Details</a> </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <th id="title">Title</th>
                <th>Author</th>
                <th>Category</th>
                <th>Create Date</th>
                <th>News Date</th>
                <th>Country</th>
            </tr>
        </tfoot>
    </table>
</div>

<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
<script src="~/js/site.js"></script>
<script>
    document.getElementById('fileInput').addEventListener('change', function () {
        var fileInput = document.getElementById('fileInput');

        if (fileInput.files.length > 0) {
            document.querySelector('form').submit();
        }
    });
</script>


<script>
    document.getElementById('fileInput').addEventListener('change', function () {
        var fileInput = document.getElementById('fileInput');
        var uploadButton = document.getElementById('uploadButton');

        if (fileInput.files.length > 0) {
            uploadButton.style.display = 'block';
        } else {
            uploadButton.style.display = 'none';
        }
    });
</script>
<script>
    document.getElementById('fileInput').addEventListener('change', function () {
        var fileInput = document.getElementById('fileInput');

        if (fileInput.files.length > 0) {
            var allowedFormats = [".xlsx"];
            var fileName = fileInput.files[0].name;
            var fileExtension = fileName.slice(((fileName.lastIndexOf(".") - 1) >>> 0) + 2);

            if (allowedFormats.includes("." + fileExtension)) {
                document.querySelector('form').submit();
            } else {
                alert("Please choose an Excel file.");
                fileInput.value = "";
            }
        }
    });
</script>